export const refs = {
  startBtn: document.querySelector('.start'),
  stopBtn: document.querySelector('.stop'),
  form: document.querySelector('.search-form'),
  swiperList: document.querySelector('.city-slider__wrapper'),
  saveFavoriteBtn: document.querySelector('.saveFavoriteBtn'),
  dateOneDay: document.querySelector('.dateOneDay'),
  month: document.querySelector('.month'),
  timer: document.querySelector('.timeSpan'),
  searchInput: document.querySelector('.search-input'),
  buttonsOneOrFive: document.querySelector('.buttonsOneOrFive'),
  weatherWrapperOneDay: document.querySelector('.weather__wrapper-oneDay'),
  weatherWrapperOneDayDate: document.querySelector(
    '.weather__wrapper-oneDayDate'
  ),
  weatherWrapper: document.querySelector('.weather__wrapper'),
  wrapper: document.querySelector('.wrapper'),
  chart: document.querySelector('.chart'),
  weatherChart: document.querySelector('.weather-chart'),
  showChart: document.querySelector('.btn-show-chart'),
  showChartText: document.querySelector('.show-chart'),
  weatherInfo: document.querySelector('.weather-info'),
  weatherCard: document.querySelector('.weather__card'),
  moreInfo: document.querySelector('.more-info'),
  moreInfoList: document.querySelector('.more-info-list'),
  swiperList: document.querySelector('.city-slider__wrapper'),
  weatherWrapperOneDay: document.querySelector('.weather__wrapper-oneDay'),
  cityNameForFiveDaysInfo: document.querySelector('.city-name'),
  weatherInfo: document.querySelector('.weather-info'),
};
